In [1]:
import pandas as pd, re, json

# read data
df_KM = pd.read_csv("data/min_KM.txt", sep='\t', names=["EC","substrate","organism","KM","star"])
df_kcat = pd.read_csv("data/max_KCAT.txt", sep='\t', names=["EC","substrate","organism","kcat","star"])

In [2]:
# delete star column
del df_KM['star']
del df_kcat['star']

In [3]:
# remove 'EC'
trim = lambda x: x.split('EC')[1]
df_KM['EC'] = df_KM['EC'].apply(trim)
df_kcat['EC'] = df_kcat['EC'].apply(trim)

In [4]:
# filter organism
trim = lambda x: x.split('//')[0]
df_KM['organism'] = df_KM['organism'].apply(trim)
df_kcat['organism'] = df_kcat['organism'].apply(trim)

In [5]:
# Remove D-, L-, DL- and similar from the beginning of substrates
def remove_dl(substrate):
    regex = '^d-|^l-|^dl-|^\(r\)-|^\(s\)-|^\(\+\)-|^\(\-\)-'
    return re.sub(regex, '', substrate)

# remove dl-info
df_KM['substrate'] = df_KM['substrate'].apply(remove_dl)
df_kcat['substrate'] = df_kcat['substrate'].apply(remove_dl)

In [7]:
# sort by ascending KM and save only minimum value (?)
df_KM = df_KM.sort_values(by=['EC','substrate','organism','KM'])
keep_min = ~df_KM[['EC','substrate','organism']].duplicated() # False for duplicates with higher KM
df_KM = df_KM[keep_min].reset_index(drop=True)

In [8]:
# sort by descending kcat and save only maximum value (?)
df_kcat = df_kcat.sort_values(by=['EC','substrate','organism','kcat'], ascending=[1, 1, 1, 0])
keep_max = ~df_kcat[['EC','substrate','organism']].duplicated() # False for duplicates with lower kcat
df_kcat = df_kcat[keep_max].reset_index(drop=True)

In [10]:
# merge dataframes
df = pd.merge(df_kcat, df_KM, how='outer')

In [11]:
df['e'] = df['kcat']/df['KM']
df.head(20)

,EC,substrate,organism,kcat,KM,e
0,1.1.1.1,(+)-1-indanol,thermus thermophilus,61.400,4.200,14.619048
1,1.1.1.1,(+)-alpha-tetraol,thermus thermophilus,57.000,4.200,13.571429
2,1.1.1.1,(-)-1-phenylethanol,thermus thermophilus,1.100,18.100,0.060773
3,1.1.1.1,(2e)-but-2-en-1-ol,yokenella sp.,101.000,9.100,11.098901
4,1.1.1.1,(2e)-but-2-enal,yokenella sp.,405.000,3.300,122.727273
5,1.1.1.1,1-butanol,aeropyrum pernix,0.410,0.596,0.687919
6,1.1.1.1,1-butanol,mesocricetus auratus,7.500,NaN,NaN
7,1.1.1.1,1-butanol,rattus norvegicus,48.800,0.170,287.058824
8,1.1.1.1,1-butanol,sulfolobus solfataricus,3.100,0.080,38.750000
9,1.1.1.1,1-heptanol,sulfolobus solfataricus,1.600,0.038,42.105263
10,1.1.1.1,1-hexanol,aeropyrum pernix,0.370,0.147,2.517007
11,1.1.1.1,1-hexanol,mesocricetus auratus,3.030,NaN,NaN
12,1.1.1.1,1-hexanol,sulfolobus solfataricus,2.000,0.035,57.142857
13,1.1.1.1,1-indanol,sulfolobus acidocaldarius,13.700,2.400,5.708333
14,1.1.1.1,1-indanol,thermus thermophilus,61.400,4.200,14.619048
15,1.1.1.1,1-indanone,thermus thermophilus,8.300,27.600,0.300725
16,1.1.1.1,1-octanol,geobacillus thermodenitrificans,260.700,3.880,67.190722
17,1.1.1.1,1-octanol,homo sapiens,2.830,0.390,7.256410
18,1.1.1.1,1-octanol,rattus norvegicus,60.800,0.025,2432.000000
19,1.1.1.1,1-pentanol,aeropyrum pernix,0.450,0.396,1.136364
20,1.1.1.1,1-pentanol,homo sapiens,0.183,27.000,0.006778
21,1.1.1.1,1-pentanol,rattus norvegicus,48.800,0.080,610.000000
22,1.1.1.1,1-pentanol,sulfolobus solfataricus,2.500,0.027,92.592593
23,1.1.1.1,"1-phenyl-1,2-propandione",thermus thermophilus,17.100,5.900,2.898305
24,1.1.1.1,"1-phenyl-1,2-propanedione",sulfolobus acidocaldarius,5.300,5.000,1.060000
25,1.1.1.1,"1-phenyl-1,2-propanedione",thermus thermophilus,17.100,5.900,2.898305
26,1.1.1.1,1-phenylethanol,thermococcus kodakarensis,35.700,244.000,0.146311
27,1.1.1.1,1-phenylethanol,thermus thermophilus,1.100,18.100,0.060773
28,1.1.1.1,1-propanol,aeropyrum pernix,0.260,1.030,0.252427
29,1.1.1.1,1-propanol,sulfolobus solfataricus,2.600,0.240,10.833333

In [12]:
print(len(df))

# NaN-values for each coumn
df.isnull().sum().reset_index(name='NaN')

46898
71516

       index    NaN
0         EC      0
1  substrate      0
2   organism      0
3       kcat  41625
4         KM   5273
5          e  46898

In [15]:
with open("data/substrates_filtered.json",'r') as f:
    data = json.loads(f.read())

EC_KM = df_KM.EC.unique()
EC_Kcat = df_kcat.EC.unique()
EC = df.EC.unique()

In [24]:
import random
ec = random.choice(EC)
display(df[df['EC'] == ec])

print('\n')
substrates = [x.lower() for x in data[ec]['first_substrate']]
print(substrates)

,EC,substrate,organism,kcat,KM,e
12093,2.7.1.2,atp,homo sapiens,68.4,2.300000e-07,2.973913e+08
12094,2.7.1.2,atp,leishmania major,317.0,3.500000e-01,9.057143e+02
12095,2.7.1.2,atp,trypanosoma cruzi,1492.0,3.600000e-01,4.144444e+03
12096,2.7.1.2,beta-d-glucose,homo sapiens,166.0,NaN,NaN
12097,2.7.1.2,glucose,escherichia coli k-12,410.0,NaN,NaN
12098,2.7.1.2,glucose,homo sapiens,67.6,1.500000e-01,4.506667e+02
12099,2.7.1.2,glucose,leishmania major,317.0,NaN,NaN
12100,2.7.1.2,glucose,thermotoga maritima,92.6,NaN,NaN
12101,2.7.1.2,glucose,trypanosoma cruzi,1492.0,1.000000e+00,1.492000e+03
52068,2.7.1.2,2-deoxy-d-glucose,homo sapiens,NaN,1.900000e+00,NaN
52069,2.7.1.2,2-deoxyglucose,homo sapiens,NaN,1.800000e+01,NaN
52070,2.7.1.2,6-n-(carboxyethyl)atp,geobacillus stearothermophilus,NaN,6.700000e-01,NaN
52071,2.7.1.2,6-n-(carboxyethyl)atp,zymomonas mobilis,NaN,5.000000e-01,NaN
52072,2.7.1.2,6-n-(carboxymethyl)atp,geobacillus stearothermophilus,NaN,6.500000e-01,NaN
52073,2.7.1.2,6-n-(carboxymethyl)atp,zymomonas mobilis,NaN,5.500000e-01,NaN
52074,2.7.1.2,6-n-(succinyl)atp,geobacillus stearothermophilus,NaN,1.000000e+00,NaN
52075,2.7.1.2,6-n-(succinyl)atp,zymomonas mobilis,NaN,3.800000e-01,NaN
52076,2.7.1.2,6-n-[n-(6-aminohexhyl)carbamoyl]atp,geobacillus stearothermophilus,NaN,5.000000e-01,NaN
52077,2.7.1.2,6-n-[n-(6-aminohexhyl)carbamoyl]atp,zymomonas mobilis,NaN,1.250000e+00,NaN
52078,2.7.1.2,alpha-d-glucose,geobacillus stearothermophilus,NaN,1.500000e-01,NaN
52079,2.7.1.2,atp,aeropyrum pernix,NaN,5.000000e-01,NaN
52080,2.7.1.2,atp,dictyostelium discoideum,NaN,1.100000e+00,NaN
52081,2.7.1.2,atp,escherichia coli,NaN,5.000000e-01,NaN
52082,2.7.1.2,atp,geobacillus stearothermophilus,NaN,1.300000e-01,NaN
52083,2.7.1.2,atp,lysinibacillus sphaericus c3-41,NaN,5.200000e-01,NaN
52084,2.7.1.2,atp,paracoccus versutus,NaN,7.800000e-01,NaN
52085,2.7.1.2,atp,saccharomyces cerevisiae,NaN,5.000000e-02,NaN
52086,2.7.1.2,atp,streptococcus mutans,NaN,2.100000e-01,NaN
52087,2.7.1.2,atp,yarrowia lipolytica,NaN,2.100000e-01,NaN
52088,2.7.1.2,atp,zymomonas mobilis,NaN,4.000000e-01,NaN
52089,2.7.1.2,ctp,zymomonas mobilis,NaN,5.600000e-01,NaN
52090,2.7.1.2,fructose,homo sapiens,NaN,4.700000e+00,NaN
52091,2.7.1.2,glucose,aeropyrum pernix,NaN,5.400000e-02,NaN
52092,2.7.1.2,glucose,aspergillus niger,NaN,6.300000e-02,NaN
52093,2.7.1.2,glucose,botrytis cinerea,NaN,4.800000e-02,NaN
52094,2.7.1.2,glucose,caldanaerobacter subterraneus subsp. tengconge...,NaN,2.400000e+00,NaN
52095,2.7.1.2,glucose,dictyostelium discoideum,NaN,1.200000e-01,NaN
52096,2.7.1.2,glucose,escherichia coli,NaN,1.500000e-01,NaN
52097,2.7.1.2,glucose,lysinibacillus sphaericus c3-41,NaN,3.100000e-01,NaN
52098,2.7.1.2,glucose,paracoccus versutus,NaN,8.600000e-01,NaN
52099,2.7.1.2,glucose,rattus norvegicus,NaN,7.400000e+00,NaN
52100,2.7.1.2,glucose,saccharomyces cerevisiae,NaN,2.800000e-02,NaN
52101,2.7.1.2,glucose,streptococcus mutans,NaN,6.100000e-01,NaN
52102,2.7.1.2,glucose,urocitellus undulatus,NaN,2.000000e+00,NaN
52103,2.7.1.2,glucose,zymomonas mobilis,NaN,9.500000e-02,NaN
52104,2.7.1.2,gtp,zymomonas mobilis,NaN,2.500000e-01,NaN
52105,2.7.1.2,itp,zymomonas mobilis,NaN,3.600000e-01,NaN
52106,2.7.1.2,mannose,homo sapiens,NaN,8.000000e-02,NaN
52107,2.7.1.2,mgatp2-,zymomonas mobilis,NaN,1.900000e-01,NaN
52108,2.7.1.2,utp,zymomonas mobilis,NaN,6.300000e-01,NaN

['6-n-(carboxyethyl)atp', '6-n-(carboxymethyl)atp', '6-n-(succinyl)atp', '6-n-[n-(6-aminohexhyl)carbamoyl]atp', 'adp', 'atp', 'ctp', 'd-glucose', 'gtp', 'itp', 'utp', "adenosine 5'-triphosphate-polyamidoamine dendrimer"]

In [60]:

counter_KM = 0 
for ec in EC_KM:
    try:
        natural = [x.lower() for x in data[ec]['first_substrate']]
        df_tmp = df_KM[df_KM['EC'] == ec]
        indexNames = df_tmp[~df_tmp['substrate'].isin(natural)].index
        df_KM.drop(indexNames, inplace=True)
    except:
        counter_KM += 1

counter_Kcat = 0
for ec in EC_Kcat:
    try: 
        natural = [x.lower() for x in data[ec]['first_substrate']]
        df_tmp = df_Kcat[df_Kcat['EC'] == ec]
        indexNames = df_tmp[~df_tmp['substrate'].isin(natural)].index
        df_Kcat.drop(indexNames, inplace=True)
    except:
        counter_Kcat += 1